version: 2
snapshot:
  widths:
    - 375
    - 480
    - 720
    - 1280
    - 1440
    - 1920
  minHeight: 1024
  percyCSS: ""
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
static:
  baseUrl: /
  files: "**/*.{html,htm}"
  ignore: ""
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
